dojos_and_ninjas/dojo_ninja_app/urls.py
from django.urls import path
from . import views

app_name = 'create'

urlpatterns = [
    path('', views.index),
    path('dojos/new', views.create_dojo, name='dojo'),
    path('ninjas/new', views.create_ninja, name='ninja'),
    path('dojos/<int:dojo_id>/delete', views.delete_dojo, name='delete')
]

dojos_and_ninjas/dojos_and_ninjas/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dojo_ninja_app.urls'))
    # path('admin/', admin.site.urls),
]

dojos_and_ninjas/dojo_ninja_app/models.py
from django.db import models

# Create your models here.
class Dojo(models.Model):
    name = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Ninja(models.Model):
    dojo = models.ForeignKey(Dojo, related_name = 'ninjas', on_delete = models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

dojos_and_ninjas/dojo_ninja_app/views.py
from django.shortcuts import render, redirect
from .models import Dojo
from .models import Ninja

# Create your views here.
def index(request):
    content = {
        'all_dojos': Dojo.objects.all()
    }
    print(content)
    return render(request, 'index.html', content)

def create_dojo(request):
    Dojo.objects.create(name = request.POST['name'], 
                        city = request.POST['city'], 
                        state = request.POST['state'])
    return redirect('/')

def create_ninja(request):
    this_dojo = Dojo.objects.get(id=request.POST['dojo_id'])
    Ninja.objects.create(first_name = request.POST['first_name'],
                        last_name = request.POST['last_name'],
                        dojo = this_dojo)
    return redirect('/')

def delete_dojo(request, dojo_id):
    dojo_to_delete = Dojo.objects.get(id=dojo_id)
    dojo_to_delete.delete()
    return redirect('/')

dojos_and_ninjas/dojo_ninja_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dojos and Ninjas</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="container">
        <div id="top">
            <div class="forms">
                <h2>Add a Dojo</h2>
                <form action="{% url 'create:dojo' %}", method="post">
                    {% csrf_token %}
                    <p>
                        <label>Name</label>
                        <input type="text" name="name">
                    </p>
                    <p>
                        <label>City</label>
                        <input type="text" name="city">
                    </p>
                    <p>
                        <label>State</label>
                        <input type="text" name="state">
                    </p>
                    <input type="submit" value="Add">
                </form>
            </div>
            <div class="forms">
                <h2>Add a Ninja</h2>
                <form action="{% url 'create:ninja' %}", method="post">
                    {% csrf_token %}
                    <p>
                        <label>First Name</label>
                        <input type="text" name="first_name">
                    </p>
                    <p>
                        <label>Last Name</label>
                        <input type="text" name="last_name">
                    </p>
                    <p>
                        <label>Dojo</label>
                        <select name="dojo_id" id="dojo_id">
                            {% for dojo in all_dojos %}
                                <option value="{{ dojo.id }}">{{ dojo.name }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <input type="submit" value="Add">
                </form>
            </div>
        </div>
        <hr>
        <div id="bottom">
            <h2>All the Dojos</h2>
            {% if all_dojos %}
                {% for dojo in all_dojos %}
                    <h3>Ninjas at the {{ dojo.name }} - {{ dojo.ninjas.all.count }}</h3>
                    <ul>
                        {% for ninja in dojo.ninjas.all %}
                            <li>{{ ninja.first_name }} {{ ninja.last_name }}</li>
                        {% endfor %}
                    </ul>
                    <a href="{% url 'create:delete' dojo_id=dojo.id %}">Delete Dojo</a>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</body>
</html>