tv_shows/shows/urls.py
from django.urls import path
from . import views

app_name = 'shows'

urlpatterns = [
    path('', views.index),
    path('shows', views.dashboard, name='dashboard'),
    path('shows/create', views.create_show, name='create_show'),
    path('shows/new', views.new_show, name='new_show'),
    path('shows/<int:show_id>', views.one_show, name='one_show'),
    path('shows/<int:show_id>/edit', views.edit_show, name='edit'),
    path('shows/<int:show_id>/update', views.update_show, name='update'),
    path('shows/<int:show_id>/destroy', views.delete_show, name='delete')
]

tv_shows/tv_shows/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shows.urls'))
    # path('admin/', admin.site.urls),
]

tv_shows/shows/models.py
from django.db import models

# Create your models here.
class Show(models.Model):
    title = models.CharField(max_length=45)
    network = models.CharField(max_length=45)
    desc = models.TextField()
    release = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

tv_shows/shows/views.py
from django.shortcuts import render, redirect
from .models import Show

# Create your views here.

# Create methods
def new_show(request):
    return render(request, 'new_show.html')

def create_show(request):
    created_show =Show.objects.create(title = request.POST['title'],
                                    network = request.POST['network'],
                                    desc = request.POST['desc'],
                                    release = request.POST['release'])
    return redirect(f'/shows/{created_show.id}')

# Read methods
def index(request):
    return redirect('/shows')

def dashboard(request):
    content = {
        'all_shows': Show.objects.all()
    }
    return render(request, 'dashboard.html', content)

def one_show(request, show_id):
    content = {
        'show': Show.objects.get(id=show_id)
    }
    return render(request, 'display_show.html', content)

# Update methods
def edit_show(request, show_id):
    show = Show.objects.get(id=show_id)
    content = {
        'show': show,
    }
    return render(request, 'edit_show.html', content)

def update_show(request, show_id):
    show_to_update = Show.objects.get(id=show_id)
    show_to_update.title = request.POST['title']
    show_to_update.network = request.POST['network']
    show_to_update.desc = request.POST['desc']
    if request.POST['release']:
        show_to_update.release = request.POST['release']
    show_to_update.save()
    return redirect(f'/shows/{show_id}')

# Delete methods
def delete_show(request, show_id):
    Show.objects.get(id=show_id).delete()
    return redirect('/shows')

tv_shows/shows/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <h1>All Shows</h1>
        <table style="border: 3px solid black;">
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Network</th>
                <th>Release Date</th>
                <th>Actions</th>
            </tr>
            {% for show in all_shows %}
                <tr>
                    <td>{{ show.id }}</td>
                    <td>{{ show.title }}</td>
                    <td>{{ show.network }}</td>
                    <td>{{ show.release }}</td>
                    <td>
                        <a href="{% url 'shows:one_show' show_id=show.id %}">Show</a> | 
                        <a href="{% url 'shows:edit' show_id=show.id %}">Edit</a> | 
                        <a href="{% url 'shows:delete' show_id=show.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <a href="{% url 'shows:new_show' %}">Add a New Show</a>
    </div>
</body>
</html>

tv_shows/shows/templates/display_show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Display Show</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <div class="nav-bar">
            <h1>TV Show {{ show.id }}</h1>
            <a href="{% url 'shows:dashboard' %}">Go Back</a>
        </div>
        <div>
            <p>Title: {{ show.title }}</p>
            <p>Network: {{ show.network }}</p>
            <p>Release Date: {{ show.release }}</p>
            <p>Description: {{ show.desc }}</p>
        </div>
        <p>Last Updated: {{ show.updated_at }}</p>
        <div>
            <a href="{% url 'shows:edit' show_id=show.id %}">Edit</a> | 
            <a href="{% url 'shows:delete' show_id=show.id %}">Delete</a>
        </div>
    </div>
</body>
</html>

tv_shows/shows/templates/edit_show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit a Show</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <div class="nav-bar">
            <h1>Edit Show</h1>
            <a href="{% url 'shows:dashboard' %}">Go Back</a>
        </div>
        <div>
            <form action="{% url 'shows:update' show_id=show.id %}" method="post">
                {% csrf_token %}
                <label>Title
                    <input type="text" name="title" value="{{ show.title }}">
                </label>
                <div>
                    <label>Network
                        <input type="text" name="network" value="{{ show.network }}">
                    </label>
                    <label>Release Date
                        <input type="date" name="release" value="{{ show.release }}">
                    </label>
                </div>
                <label>Description
                    <textarea name="desc" cols="30" rows="10">{{ show.desc }}</textarea>
                </label>
                <input type="submit" value="Update">
            </form>
        </div>
    </div>
</body>
</html>

tv_shows/shows/templates/new_show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add a Show</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <div class="nav-bar">
            <h1>Add a New Show</h1>
            <a href="{% url 'shows:dashboard' %}">Go Back</a>
        </div>
        <div>
            <form action="{% url 'shows:create_show' %}" method="post">
                {% csrf_token %}
                <label>Title
                    <input type="text" name="title">
                </label>
                <div>
                    <label>Network
                        <input type="text" name="network">
                    </label>
                    <label>Release Date
                        <input type="date" name="release">
                    </label>
                </div>
                <label>Description
                    <textarea name="desc" cols="30" rows="10"></textarea>
                </label>
                <input type="submit" value="Create">
            </form>
        </div>
    </div>
</body>
</html>