books_authors_proj/books_authors_app/urls.py
from django.urls import path
from . import views

app_name = 'books_authors'

urlpatterns = [
    path('', views.index),
    path('books/create', views.create_book, name='new_book'),
    path('books/<int:book_id>', views.show_book, name='display_book'),
    path('books/add_author', views.add_author, name='add_author'),
    path('authors', views.author_index),
    path('authors/create', views.create_author, name='new_author'),
    path('authors/<int:author_id>', views.show_author, name='display_author'),
    path('author/add_book', views.add_book, name='add_book'),
]

books_authors_proj/books_authors_proj/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('books_authors_app.urls'))
    # path('admin/', admin.site.urls),
]

books_authors_proj/books_authors_app/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255)
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Author(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    notes = models.TextField(null=True)
    books = models.ManyToManyField(Book, related_name='authors')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

books_authors_proj/books_authors_app/views.py
from django.shortcuts import render, redirect
from .models import Book
from .models import Author

# Create your views here.

# Create methods

def create_book(request):
    Book.objects.create(title = request.POST['title'],
                        desc = request.POST['desc'])
    return redirect('/')

def create_author(request):
    Author.objects.create(first_name = request.POST['first_name'],
                        last_name = request.POST['last_name'],
                        notes = request.POST['notes'])
    return redirect('/authors')


# Read methods

def index(request):
    content = {
        'all_books': Book.objects.all()
    }
    return render(request, 'index.html', content)

def author_index(request):
    content = {
        'all_authors': Author.objects.all()
    }
    return render(request, 'new_author.html', content)

def show_book(request, book_id):
    content = {
        'book': Book.objects.get(id=book_id),
        'all_authors': Author.objects.all()
    }
    return render(request, 'one_book.html', content)

def show_author(request, author_id):
    content = {
        'author': Author.objects.get(id=author_id),
        'all_books': Book.objects.all()
    }
    return render(request, 'one_author.html', content)

def add_author(request):
    this_book = Book.objects.get(id=request.POST['book_id'])
    this_author = Author.objects.get(id=request.POST['author_id'])
    this_book.authors.add(this_author)
    return redirect(f'/books/{this_book.id}')

def add_book(request):
    this_book = Book.objects.get(id=request.POST['book_id'])
    this_author = Author.objects.get(id=request.POST['author_id'])
    this_author.books.add(this_book)
    return redirect(f'/authors/{this_author.id}')

books_authors_proj/books_authors_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add a New Book</title>
</head>
<body>
    <div style="display: flex;">
        <div>
            <h1>Add a Book</h1>
            <form action="{% url 'books_authors:new_book' %}" method="post">
                {% csrf_token %}
                <p>
                    <label>Title</label>
                    <input type="text" name="title">
                </p>
                <p>
                    <label>Description</label>
                    <input type="text" name="desc">
                </p>
                <input type="submit" value="Add">
            </form>
        </div>
        <div>
            <table>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Action</th>
                </tr>
                {% for book in all_books %}
                    <tr>
                        <td>{{ book.id }}</td>
                        <td>{{ book.title }}</td>
                        <td><a href="{% url 'books_authors:display_book' book_id=book.id %}">View</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</body>
</html>

books_authors_proj/books_authors_app/templates/new_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add an Author</title>
</head>
<body>
    <div style="display: flex;">
        <div>
            <h1>Add an Author</h1>
            <form action="{% url 'books_authors:new_author' %}" method="post">
                {% csrf_token %}
                <p>
                    <label>First Name</label>
                    <input type="text" name="first_name">
                </p>
                <p>
                    <label>Last Name</label>
                    <input type="text" name="last_name">
                </p>
                <p>
                    <label>Notes</label>
                    <input type="text" name="notes">
                </p>
                <input type="submit" value="Add">
            </form>
        </div>
        <div>
            <table>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
                {% for author in all_authors %}
                    <tr>
                        <td>{{ author.id }}</td>
                        <td>{{ author.first_name }} {{ author.last_name }}</td>
                        <td><a href="{% url 'books_authors:display_author' author_id=author.id %}">View</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</body>
</html>

books_authors_proj/books_authors_app/templates/one_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Display an Author</title>
</head>
<body>
    <h1>{{ author.first_name }} {{ author.last_name }}</h1>
    <p>ID: {{ author.id }}</p>
    <p>Notes: {{ author.notes }}</p>
    <p>Books:</p>
    <ul>
        {% for book in author.books.all %}
            <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
    <form action="{% url 'books_authors:add_book' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="author_id" value="{{ author.id }}">
        <select name="book_id" id="book_id">
            {% for book in all_books %}
                {% if book not in author.books.all %}
                    <option value="{{ book.id }}">{{ book.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <input type="submit" value="Add Book">
    </form>
</body>
</html>

books_authors_proj/books_authors_app/templates/one_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Display a Book</title>
</head>
<body>
    <h1>{{ book.title }}</h1>
    <p>ID: {{ book.id }}</p>
    <p>Description: {{ book.desc }}</p>
    <p>Authors:</p>
    <ul>
        {% for author in book.authors.all %}
            <li>{{ author.first_name }} {{ author.last_name }}</li>
        {% endfor %}
    </ul>
    <form action="{% url 'books_authors:add_author' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="book_id" value="{{ book.id }}">
        <select name="author_id" id="author_id">
            {% for author in all_authors %}
                {% if author not in book.authors.all %}
                    <option value="{{ author.id }}">{{ author.first_name }} {{ author.last_name }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <input type="submit" value="Add Author">
    </form>
</body>
</html>