great_number_game/great_number_game/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('guess.urls'))
]

great_number_game/guess/urls.py
from django.urls import path
from . import views

app_name = 'guesses'

urlpatterns = [
    path('', views.index),
    path('guess_number', views.guess_number, name='guess'),
    path('destroy', views.destroy_session, name='destroy')
]

great_number_game/guess/models.py
from django.db import models

# Create your models here.

great_number_game/guess/views.py
from django.shortcuts import render, redirect
import random

# Create your views here.
def index(request):
    if 'secret_number' not in request.session:
        request.session['secret_number'] = random.randint(1, 100)
        request.session['count'] = 5
        request.session['message'] = None
        request.session['correct'] = False
    return render(request, 'index.html')

def guess_number(request):
    if request.session['count'] == 0: return redirect('/')
    if request.session['secret_number'] == int(request.POST['guess']):
        request.session['message'] = 'That was the number! Play again.'
        request.session['correct'] = True
        request.session['count'] = 0
        return redirect('/')
    elif request.session['secret_number'] < int(request.POST['guess']):
        request.session['message'] = 'Too high!'
        request.session['count'] -= 1
    else:
        request.session['message'] = 'Too low!'
        request.session['count'] -= 1
    if request.session['count'] == 0 and request.session['correct'] == False:
        request.session['message'] = 'Game over!'
    return redirect('/')

def destroy_session(request):
    del request.session['secret_number']
    del request.session['count']
    del request.session['message']
    return redirect('/')

great_number_game/guess/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Great Number Game</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>Welcome to the Great Number Game!</h1>
    <p>I am thinking of a number between 1 and 100.</p>
    <p>Take a guess!</p>
    <!-- <p>The secret number is: {{ request.session.secret_number }}</p> -->

    {% if request.session.message %}
        {% if request.session.correct %}
            <p class="message" style="background-color: green;">{{ request.session.message }}</p>
        {% elif request.session.count == 0 %}
            <p class="message" style="background-color: red;">{{ request.session.message }}</p>
            <p>It was {{ request.session.secret_number }}</p>
        {% else %}
            <p class="message" style="background-color: red;">{{ request.session.message }}</p>
        {% endif %}       
    {% endif %}

    <form action="{% url 'guesses:guess' %}" method="post">
        {% csrf_token %}
        <input type="number" name="guess">
        <input id="guess" type="submit" value="Guess">
    </form>
    <a id="reset" href="{% url 'guesses:destroy' %}">Reset Game</a>
    <p>Guesses left: {{ request.session.count }}</p>
</body>
</html>